// Placeholder guide content — write the real step-by-step copy once the
// full application is finished. Every chapter here just needs a `route` so
// the "?" icon on that page can deep-link to its chapter (?chapter=<id>).

const guideChapters = [
  {
    id: 'dashboard',
    order: 1,
    title: 'Dashboard',
    route: '/dashboard',
    description: 'Your at-a-glance view of how every channel is performing.',
    readTime: '2 min read',
    content: [
      'The Dashboard is the first thing you see after signing in — a snapshot of follower growth, engagement rate, posts published this month, and total reach.',
      'Quick Actions let you jump straight into creating a post, connecting an account, or building a campaign without hunting through the sidebar.',
      'Scheduled Posts and Recent Activity keep you updated on what is coming up next and what your team just did.',
    ],
  },
  {
    id: 'social-accounts',
    order: 2,
    title: 'Social Accounts',
    route: '/social-accounts',
    description: 'Connect every platform you publish to from one place.',
    readTime: '2 min read',
    content: [
      'Each card shows one platform — its connection status, follower count, and when it last synced.',
      'Connect New Account (or Connect on a card) opens the Connect account page — pick the platform you want from the list.',
      'The next page shows a short step-by-step guide for that platform: where to create a developer app, which permissions to tick, and which keys to copy. Use the "Open ..." button to jump straight to that platform\'s own developer site.',
      'Paste the keys into the form, press Test connection, and once it passes, Save & connect. Editing any field asks you to test again, so what you save is always what you tested.',
      'Every connection uses your own developer credentials for that platform, so Social never bills you for it — any cost is between you and the platform.',
      'For platforms that sell a paid API plan with more data (X), the form asks which plan your key is on. That choice controls how much profile detail the Inbox can show.',
    ],
  },
  {
    id: 'posts',
    order: 3,
    title: 'Posts & the Composer',
    route: '/posts',
    description: 'Write once, schedule everywhere, and track every post you publish.',
    readTime: '3 min read',
    content: [
      'Posts lists everything you have created, filterable by status — draft, scheduled, published, or failed.',
      'Create Post opens the composer: pick platforms, write your caption, attach media, and either publish immediately or schedule it for later.',
      'The Schedule field uses the app\'s date and time pickers — click the calendar or clock icon to open them.',
      'The cards at the top count your posts by status — Draft, Scheduled, Published, Pending Approval, Failed and Rejected. Click a card to filter the list to it; click it again to clear.',
      'Tick the checkboxes to act on many posts at once — the Move to draft and Delete buttons above the table are greyed out until you tick a row. When you have a lot of posts, choose how many to show per page (10, 25, 50, 100, 150 or All) above the table and move between pages below it.',
    ],
  },
  {
    id: 'calendar',
    order: 4,
    title: 'Calendar',
    route: '/calendar',
    description: 'See everything scheduled across every channel, laid out by day.',
    readTime: '1 min read',
    content: [
      'Switch between month and list views to plan around campaigns and busy days.',
      'Click any day to see what is scheduled, or jump straight into creating a new post for that date.',
    ],
  },
  {
    id: 'campaigns',
    order: 5,
    title: 'Campaigns',
    route: '/campaigns',
    description: 'Group related posts under one goal and track them together.',
    readTime: '2 min read',
    content: [
      'Create Campaign sets a name, objective, date range, and the platforms it runs on.',
      'Open a campaign to see its full team, timeline, and combined performance across every post attached to it.',
    ],
  },
  {
    id: 'ads',
    order: 6,
    title: 'Ads (paid promotion)',
    route: '/ads',
    description: 'Run paid ads on Facebook, Instagram, YouTube and more, and see exactly what your money did.',
    readTime: '3 min read',
    content: [
      'Ads are paid promotion: you pay a platform like Meta (Facebook and Instagram) or Google (YouTube) to show your post or offer to more people. Social helps you set the ad up in one place and shows the results in charts.',
      'First connect your own ad account: Ads → Ad accounts → pick the network → follow the short guide and paste your details. The ad platforms’ APIs are free, and the money you spend is billed by the platform to your own ad account — Social never charges for ads or takes a cut.',
      'An ad also appears as one of your social profiles — a Facebook Page, an Instagram account, a YouTube channel. Those come from Social Accounts, where Facebook and Instagram are connected separately. So Meta Ads lists both and shows which one is connected; if Instagram is missing you can still advertise on Facebook, and the Create Ad step greys out Instagram until you connect it. Cards on the Social Accounts page show "Ads ready" or "Set up ads" so you can see at a glance.',
      'Create Ad walks you through six steps: goal, where it runs, the ad itself (text, headline, button, link, image), who should see it, budget and dates, then a final review. The preview and a rough results estimate update as you go, and you can save a draft at any time.',
      'New ads go to the platform for review first (usually within 24 hours) and then start on the date you chose. Your budget is a ceiling — the platform never spends more than you set.',
      'The Ads overview shows spend, impressions, clicks, CTR, cost per click and results, with a chart you can switch between metrics and compare against the previous period. Filter by period, platform or status, tick ads to pause, resume or delete several at once, or open an ad for its day-by-day numbers.',
      'Download report gives you a CSV summary (one row per ad), a day-by-day CSV, or a PDF report. Open the PDF option and choose "Save as PDF" in the print window. Reports respect the filters you have set.',
    ],
  },
  {
    id: 'recycling',
    order: 7,
    title: 'Content Recycling',
    route: '/recycling',
    description: 'Automatically re-share your best evergreen posts on a schedule.',
    readTime: '1 min read',
    content: [
      'Add any published post to the recycling queue and pick how often it should go back out — every 2, 30, 60 or 90 days.',
      'Pause a post at any time without losing its schedule, or remove it from the queue entirely.',
    ],
  },
  {
    id: 'inbox',
    order: 8,
    title: 'Inbox, Comments & Mentions',
    route: '/inbox',
    description: 'Every conversation, comment, and mention in one engagement hub.',
    readTime: '2 min read',
    content: [
      'Inbox brings direct messages from every connected platform into a single thread list.',
      'Comments and Mentions split out public activity on your posts and brand mentions elsewhere, so nothing gets missed.',
      'The panel on the right of a conversation shows what the platform itself tells us about the person — username, platform ID, followers, following, posts, bio, whether they are verified, and whether you follow each other. What appears depends on the platform: Instagram, Mastodon, Bluesky, YouTube and Pinterest share a lot for free, while Facebook and LinkedIn share very little.',
      'X only shares profile details if your own X API key is on a paid plan. Choose "Paid plan" when you connect X in Social Accounts and the panel fills in followers, bio, location and more; on the free plan it shows a small hint instead. Social never pays for any of this — the plan is yours.',
    ],
  },
  {
    id: 'analytics',
    order: 9,
    title: 'Analytics',
    route: '/analytics',
    description: 'Understand what is working, broken down by channel and by post.',
    readTime: '2 min read',
    content: [
      'Analytics Overview shows top-level trends — followers, engagement, and reach over a date range you choose.',
      'Content Analytics ranks your individual posts so you can see exactly which ones are driving results.',
    ],
  },
  {
    id: 'approvals',
    order: 10,
    title: 'Approvals',
    route: '/approvals',
    description: 'Review content before it goes live, with a full comment trail.',
    readTime: '1 min read',
    content: [
      'Anything submitted for review lands here. Open a request to read the post, see prior comments, and approve or reject it.',
      'Rejecting a post requires a reason, so the author knows exactly what to fix.',
    ],
  },
  {
    id: 'media-library',
    order: 11,
    title: 'Media Library',
    route: '/media',
    description: 'Every image and video your team has uploaded, organized by folder.',
    readTime: '1 min read',
    content: [
      'Upload files here once and reuse them across any post, instead of re-uploading the same asset every time. Images open a crop window first, with a live size and an optional compress switch.',
      'The bar at the top shows how much space is used, split between the app server and any external storage you connected. You can also add a picture that is already online by pasting its link — nothing is copied.',
      'Each card shows where a file is stored, where it is used, and a Copy link button. Use the crop button to re-crop an image you uploaded.',
      'Before you delete a file, the app checks where it is used. Files in published posts are safe to remove — Instagram, Facebook and the other platforms keep their own copy, so live posts are not touched. Files needed by a scheduled post, draft, recycling item or email will show a warning, because deleting them would make those fail.',
      'Free up space removes old files (30, 60, 90 or 180 days) that nothing needs any more. It never touches files a scheduled post, draft, recycling item or email still uses.',
      'Where new uploads are saved is chosen in Settings → Storage.',
    ],
  },
  {
    id: 'links',
    order: 12,
    title: 'Link Shortener',
    route: '/links',
    description: 'Create trackable short links for anything you share, on your own domain.',
    readTime: '1 min read',
    content: [
      'Create Link turns any long URL into a short one on your own domain — no third-party shortener, so there is nothing to pay for as you grow.',
      'Each link tracks clicks over time so you can see which posts are actually driving traffic.',
    ],
  },
  {
    id: 'users-roles',
    order: 13,
    title: 'Users & Roles',
    route: '/users',
    description: 'Control who has access to your workspace, and exactly what they can do.',
    readTime: '2 min read',
    content: [
      'The People tab lists everyone with access — invite new teammates, change their role, or remove access.',
      'Roles & Permissions lets you build custom roles and tick exactly which actions each one is allowed to take.',
    ],
  },
  {
    id: 'activity-log',
    order: 14,
    title: 'Activity Log',
    route: '/activity-logs',
    description: 'A complete, filterable audit trail of who did what, and when.',
    readTime: '2 min read',
    content: [
      'Every important action in the workspace is recorded — filter by person, action type, section, or date range to find what you need.',
      'Click any entry to see full details, including a before/after comparison when something was changed.',
    ],
  },
  {
    id: 'system-emails',
    order: 15,
    title: 'System Emails',
    route: '/system-emails',
    description: 'Every automatic email Social can send — preview, edit, or turn any of them off.',
    readTime: '2 min read',
    content: [
      'Pick an email on the left to Preview it, Edit its subject and HTML, manage Images used inside it, or see its Details — who receives it and when it is sent.',
      'Reset to Default throws away your edits and restores exactly what it shipped with, even months later.',
      'The Email language box at the top switches which language you are previewing and editing. Every email has its own copy in every language, so editing the Hindi one never changes the Arabic one, and people receive the email in the language set on their own profile. You can type in any language — the text direction follows it.',
      'The switch next to each email turns automatic sending on or off — Send test still works while it is off, so you can check how it looks first.',
    ],
  },
  {
    id: 'settings',
    order: 16,
    title: 'Settings',
    route: '/settings',
    description: 'Your account, your workspace defaults, and your privacy choices.',
    readTime: '2 min read',
    content: [
      'General covers workspace-wide defaults like timezone. Account is where you manage your own profile.',
      'Language is where you pick the language you see the app in, and which of the 21 supported languages your workspace offers in the header menu, the user form and System Emails. You can also switch language any time from the globe button in the header. Arabic is shown right-to-left.',
      'Appearance is where the theme, dark mode, and brand color live. Integrations explains how platform connections use your own API credentials.',
      'Storage is where you connect your own storage — Amazon S3, Cloudflare R2, Backblaze B2, Wasabi, DigitalOcean Spaces, any S3-compatible service, or Google Drive — and choose whether new uploads go to the app server, your external storage, or nowhere. Use Test Connection and Test Upload before saving. Google Drive works well for keeping a library, but images that go out in posts and emails load more reliably from R2, B2 or your own server.',
    ],
  },
];

export default guideChapters;
