import brand from '../config/brand';

// Report downloads that work with no paid library and no server:
//   - CSV: a normal file download, opens in Excel / Google Sheets.
//   - PDF: opens a clean print view; "Save as PDF" in the browser's print dialog
//          produces the PDF (works in every desktop and mobile browser).

const csvCell = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`;

export function downloadCsv(filename, columns, rows) {
  const header = columns.map((column) => csvCell(column.header)).join(',');
  const lines = rows.map((row) => columns.map((column) => csvCell(column.value(row))).join(','));
  // The BOM makes Excel read ₹ and other non-English text correctly.
  const content = `﻿${[header, ...lines].join('\r\n')}`;
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

const escapeHtml = (value) =>
  String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// summary: [{ label, value }]   tables: [{ title, columns: [{ header, value(row), align? }], rows }]
// Returns false if the browser blocked the new window.
export function openPrintableReport({ title, subtitle, summary = [], tables = [] }) {
  const reportWindow = window.open('', '_blank');
  if (!reportWindow) return false;

  const summaryHtml = summary.length
    ? `<div class="summary">${summary
        .map((item) => `<div class="tile"><div class="tile-label">${escapeHtml(item.label)}</div><div class="tile-value">${escapeHtml(item.value)}</div></div>`)
        .join('')}</div>`
    : '';

  const tablesHtml = tables
    .map(
      (table) => `
      <h2>${escapeHtml(table.title)}</h2>
      <table>
        <thead><tr>${table.columns.map((column) => `<th class="${column.align || ''}">${escapeHtml(column.header)}</th>`).join('')}</tr></thead>
        <tbody>${table.rows
          .map((row) => `<tr>${table.columns.map((column) => `<td class="${column.align || ''}">${escapeHtml(column.value(row))}</td>`).join('')}</tr>`)
          .join('')}</tbody>
      </table>`
    )
    .join('');

  reportWindow.document.write(`<!doctype html>
<html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; color: #171a2b; margin: 32px; font-size: 13px; }
  header { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px solid #4f46e5; padding-bottom: 12px; margin-bottom: 20px; }
  h1 { margin: 0 0 4px; font-size: 22px; }
  .sub { color: #5c6178; }
  .brand { text-align: right; color: #5c6178; font-size: 12px; }
  h2 { font-size: 15px; margin: 26px 0 8px; }
  .summary { display: flex; flex-wrap: wrap; gap: 10px; }
  .tile { border: 1px solid #e6e8f0; border-radius: 8px; padding: 10px 14px; min-width: 130px; }
  .tile-label { color: #5c6178; font-size: 11px; }
  .tile-value { font-size: 18px; font-weight: 700; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: 7px 8px; border-bottom: 1px solid #e6e8f0; text-align: left; }
  th { background: #f5f6fa; font-size: 11px; text-transform: uppercase; letter-spacing: .03em; color: #5c6178; }
  .right { text-align: right; }
  footer { margin-top: 28px; color: #8b8fa3; font-size: 11px; }
  @media print { body { margin: 14mm; } h2 { break-after: avoid; } tr { break-inside: avoid; } }
</style></head>
<body>
  <header>
    <div><h1>${escapeHtml(title)}</h1><div class="sub">${escapeHtml(subtitle)}</div></div>
    <div class="brand"><strong>${escapeHtml(brand.legalName)}</strong><br>Generated ${escapeHtml(new Date().toLocaleString('en-IN'))}</div>
  </header>
  ${summaryHtml}
  ${tablesHtml}
  <footer>Report generated by ${escapeHtml(brand.productName)} · ${escapeHtml(brand.website)}. Spend figures come from your own ad accounts.</footer>
  <script>window.addEventListener('load', function () { setTimeout(function () { window.print(); }, 250); });</script>
</body></html>`);
  reportWindow.document.close();
  return true;
}
