/**
 * The system emails Social can send. The wording of each one (in every language) lives in
 * ./defaults/<code>.json under `mail`; this file describes WHEN it is sent and which
 * {{variables}} it may use. Admins can switch an email off and edit its wording per language
 * (those edits are stored in the database and win over the built-in text).
 */
export const EMAIL_CATALOG = [
  {
    id: "auth-password-reset",
    mailKey: "passwordReset",
    eventKey: "auth.passwordResetRequested",
    group: "account",
    whenSent: "A user requests a password reset link.",
    whoReceives: "The user who requested it",
    defaultEnabled: true,
    variables: ["{{user_name}}","{{reset_link}}","{{expires_in}}","{{app_name}}","{{company}}","{{support_email}}"],
  },
  {
    id: "auth-password-changed",
    mailKey: "passwordChanged",
    eventKey: "auth.passwordChanged",
    group: "account",
    whenSent: "A user successfully changes their password.",
    whoReceives: "The user whose password changed",
    defaultEnabled: true,
    variables: ["{{user_name}}","{{changed_at}}","{{app_name}}","{{support_email}}"],
  },
  {
    id: "auth-new-sign-in",
    mailKey: "newSignIn",
    eventKey: "auth.newSignIn",
    group: "account",
    whenSent: "A login happens from a device or location not seen before.",
    whoReceives: "The account owner",
    defaultEnabled: true,
    variables: ["{{user_name}}","{{device}}","{{location}}","{{signed_in_at}}","{{app_name}}"],
  },
  {
    id: "users-invited",
    mailKey: "invited",
    eventKey: "users.invited",
    group: "team",
    whenSent: "A Super Admin or Admin invites a new user.",
    whoReceives: "The invited user",
    defaultEnabled: true,
    variables: ["{{user_name}}","{{invited_by}}","{{company}}","{{role}}","{{accept_link}}","{{app_name}}"],
  },
  {
    id: "users-created-admin-copy",
    mailKey: "userAdded",
    eventKey: "users.created",
    group: "team",
    whenSent: "A new user is created in the workspace.",
    whoReceives: "All Super Admins",
    defaultEnabled: true,
    variables: ["{{new_user_name}}","{{new_user_email}}","{{role}}","{{added_by}}","{{users_url}}"],
  },
  {
    id: "users-role-changed",
    mailKey: "roleChanged",
    eventKey: "users.roleChanged",
    group: "team",
    whenSent: "A user's role is changed.",
    whoReceives: "The affected user",
    defaultEnabled: false,
    variables: ["{{user_name}}","{{old_role}}","{{new_role}}","{{changed_by}}","{{app_name}}"],
  },
  {
    id: "social-account-connected",
    mailKey: "accountConnected",
    eventKey: "social.accountConnected",
    group: "social",
    whenSent: "A social account is successfully connected.",
    whoReceives: "All Super Admins",
    defaultEnabled: true,
    variables: ["{{provider}}","{{account_name}}","{{connected_by}}","{{connected_at}}","{{accounts_url}}"],
  },
  {
    id: "social-token-expired",
    mailKey: "tokenExpired",
    eventKey: "social.tokenExpired",
    group: "social",
    whenSent: "A platform's API token expires or is revoked.",
    whoReceives: "All Super Admins",
    defaultEnabled: true,
    variables: ["{{provider}}","{{account_name}}","{{accounts_url}}","{{app_name}}"],
  },
  {
    id: "posts-published",
    mailKey: "postPublished",
    eventKey: "posts.published",
    group: "publishing",
    whenSent: "A post finishes publishing.",
    whoReceives: "The post author",
    defaultEnabled: false,
    variables: ["{{post_excerpt}}","{{platforms}}","{{published_at}}","{{post_url}}"],
  },
  {
    id: "posts-failed",
    mailKey: "postFailed",
    eventKey: "posts.failed",
    group: "publishing",
    whenSent: "Publishing fails because the provider refused, or the connection broke.",
    whoReceives: "The post author and all Super Admins",
    defaultEnabled: true,
    variables: ["{{post_excerpt}}","{{platforms}}","{{error_reason}}","{{posts_url}}"],
  },
  {
    id: "approvals-requested",
    mailKey: "approvalRequested",
    eventKey: "approvals.requested",
    group: "approvals",
    whenSent: "A post is submitted for approval.",
    whoReceives: "Users who can approve content",
    defaultEnabled: true,
    variables: ["{{submitted_by}}","{{post_excerpt}}","{{approvals_url}}"],
  },
  {
    id: "approvals-completed",
    mailKey: "approvalDecided",
    eventKey: "approvals.completed",
    group: "approvals",
    whenSent: "A submitted post is approved or rejected.",
    whoReceives: "The post author",
    defaultEnabled: true,
    variables: ["{{decision}}","{{post_excerpt}}","{{reviewer}}","{{reason}}","{{posts_url}}"],
  },
  {
    id: "inbox-new-comment",
    mailKey: "newComment",
    eventKey: "inbox.newComment",
    group: "engagement",
    whenSent: "A new comment comes in on a connected account.",
    whoReceives: "Users assigned to Inbox",
    defaultEnabled: false,
    variables: ["{{commenter_name}}","{{comment_text}}","{{post_excerpt}}","{{inbox_url}}"],
  },
];

export const CATALOG_BY_ID = new Map(EMAIL_CATALOG.map((email) => [email.id, email]));
export const CATALOG_BY_EVENT = new Map(EMAIL_CATALOG.map((email) => [email.eventKey, email]));
