import { brandVariables } from './builder.js';

// Sample data for "Send test": real-looking values so an admin can judge the layout.
export function sampleVariables(appUrl) {
  return {
    ...brandVariables(),
    user_name: 'Priya Sharma',
    reset_link: `${appUrl}/reset-password?token=sample`,
    expires_in: '60 minutes',
    changed_at: new Date().toUTCString(),
    device: 'Chrome on Windows',
    location: 'Mumbai, India',
    signed_in_at: new Date().toUTCString(),
    invited_by: 'Nitesh Bhardwaj',
    role: 'Editor',
    accept_link: `${appUrl}/accept-invite?token=sample`,
    new_user_name: 'Vikram Singh',
    new_user_email: 'vikram@example.com',
    added_by: 'Nitesh Bhardwaj',
    users_url: `${appUrl}/users`,
    old_role: 'Contributor',
    new_role: 'Editor',
    changed_by: 'Nitesh Bhardwaj',
    provider: 'Instagram Business',
    account_name: 'example.com',
    connected_by: 'Priya Sharma',
    connected_at: new Date().toUTCString(),
    accounts_url: `${appUrl}/social-accounts`,
    post_excerpt: 'Thank you for 25,000 followers!',
    platforms: 'Instagram, Facebook',
    published_at: new Date().toUTCString(),
    post_url: appUrl,
    error_reason: 'the connected account token expired',
    posts_url: `${appUrl}/posts`,
    submitted_by: 'Priya Sharma',
    approvals_url: `${appUrl}/approvals`,
    decision: 'approved',
    reviewer: 'Nitesh Bhardwaj',
    reason: 'Looks great — ready to publish.',
    commenter_name: 'Sara Khan',
    comment_text: 'Love this!',
    inbox_url: `${appUrl}/inbox`,
  };
}
